# Generated by Django 3.0.5 on 2020-04-07 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='prodession',
            new_name='profession',
        ),
    ]
